<?php
$timezones = array(
    'Pacific/Midway'       => "(UTC-11:00)",
    'US/Hawaii'            => "(UTC-10:00)",
    'US/Alaska'            => "(UTC-09:00)",
    'US/Pacific'           => "(UTC-08:00)",
    'US/Arizona'           => "(UTC-07:00)",
    'US/Central'           => "(UTC-06:00)",
    'US/Eastern'           => "(UTC-05:00)",
    'America/Caracas'      => "(UTC-04:30)",
    'Greenland'            => "(UTC-03:00)",
    'Atlantic/Stanley'     => "(UTC-02:00)",
    'Atlantic/Azores'      => "(UTC-01:00)",
    'Africa/Casablanca'    => "(UTC)",
    'Europe/Amsterdam'     => "(UTC+01:00)",
    'Europe/Athens'        => "(UTC+02:00)",
    'Asia/Baghdad'         => "(UTC+03:00)",
    'Asia/Baku'            => "(UTC+04:00)",
    'Asia/Karachi'         => "(UTC+05:00)",
    'Asia/Yekaterinburg'   => "(UTC+06:00)",
    'Asia/Novosibirsk'     => "(UTC+07:00)",
    'Asia/Krasnoyarsk'     => "(UTC+08:00)",
    'Asia/Irkutsk'         => "(UTC+09:00",
    'Asia/Yakutsk'         => "(UTC+10:00)",
    'Asia/Vladivostok'     => "(UTC+11:00)",
    'Asia/Magadan'         => "(UTC+12:00)",
);